services:
  backend:
    build: .
    container_name: portfolio_backend
    ports:
      - "127.0.0.1:8787:8787"
    environment:
      - PORT=8787
    env_file:
      - ./.env
    restart: unless-stopped
